### ISSUE TITLE
Delphi 10.4.1 won't compile

### ISSUE THREAD

**Issue by shineworld** [Embarcadero/Delphi4PythonExporter#2] opened 2022-02-25 07:10 UTC
As you can see in the image the exporter does not build with Delphi 10.4.1:

![image](https://user-images.githubusercontent.com/1633598/155670887-5f568288-2ad3-4008-b8a1-6b158a4583d5.png)

![image](https://user-images.githubusercontent.com/1633598/155671180-5495023d-9e6f-4c07-9ab6-dfebe533b2a3.png)

**Comment by lmbelo** [comment] 2022-02-25 19:31
@shineworld thank you for your report. I will work in a backward compatibility.

**Comment by lmbelo** [comment] 2022-03-06 00:49
We made the exporter tool backwards compatible to Delphi 10 Seattle. Can you try again, please?

**Comment by shineworld** [comment] 2022-03-07 17:13
Works at 50% :)

Basically this is what happens:

I start the IDE environment and create only a unit View.
With Tools-> Exports To Python -> Export Forms:
![image](https://user-images.githubusercontent.com/1633598/157083012-eee38ed6-ea49-477e-a874-64522a997a9f.png)
![image](https://user-images.githubusercontent.com/1633598/157083209-d7b63cbb-cccb-4bf7-9273-21e65dece905.png)

I start the IDE environment and I create a New VCL Project (which create also a Form).
With Tools-> Exports To Python -> Export Current Project:

Then the py file and property file are finely created.

**Comment by lmbelo** [comment] 2022-03-07 20:21
@shineworld, unfortunately I can't reproduce your issue. Try to attach your sample, then I can run a deeper investigate. Did you update the exporter to the latest version?

![image](https://user-images.githubusercontent.com/8376898/157111639-0c7216eb-b868-4350-be83-5555d279cc30.png)

**Comment by shineworld** [comment] 2022-03-20 16:19
Sorry @Imbelo the issue was MINE !
Pratically I've saved form name as DesktopView.pas and class as TDesktopView (manually renamed).
The form var was also DesktopView so this create the crash during form export for python.
The form was never compiled, just to export so I've missing to see the bug in my form unit.

Sorry again.
The IDE extension works perfectly.

**Comment by lmbelo** [comment] 2022-03-21 20:03
I'm glad you got it working :)
Let me close this issue once it has been resolved.

**Closed as completed by lmbelo** 2022-03-21 20:03 UTC
Labels: enhancement
